modLoader = "kotlinforforge"
loaderVersion = "[5,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "cobblehome_neoforge"
version = "${version}"
displayName = "Cobblemon NeoForge Template Sidemod"
authors = "Heitor Maciel"
description = '''
Simple Client-Side Home for Cobblemon
'''
#logoFile = ""

[[dependencies.cobblemon_neoforge_mdk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_neoforge_mdk]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_neoforge_mdk]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"
